version: "3.9"
services:
  backend:
    build: 
      context: backend
    container_name: backend
    networks:
      - postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=my_super_secret
      - DB_HOST=mb_postgres
      - DB_USER=api
      - DB_PASSWORD=password
      - DB_NAME=malwarebytes
      - DB_PORT=5432
      - HTTP_PORT=3000

  frontend:
    build: 
      context: frontend
    container_name: frontend
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:15.2
    container_name: mb_postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=api
      - POSTGRES_DB=malwarebytes

networks:
  postgres:
    driver: bridge