version: "3.9"
services:
  backend:
    build: 
      context: backend
    container_name: backend
    command: npm run start:debug
    networks:
      - postgres
    depends_on:
      - postgres
    ports:
      - 3001:3000
      - 3002:3001
      - 9229:9229
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=my_super_secret
      - DB_HOST=mb_postgres
      - DB_USER=api
      - DB_PASSWORD=password
      - DB_NAME=malwarebytes
      - DB_PORT=5432
      - HTTP_PORT=3000
      - WEBSOCKET_PORT=3001

  frontend:
    build: 
      context: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001
      - REACT_APP_WEBSOCKET_URL=ws://localhost:3002

  postgres:
    image: postgres:15.2
    container_name: mb_postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=api
      - POSTGRES_DB=malwarebytes

networks:
  postgres:
    driver: bridge